feat: Enhance configuration and functionality across multiple tools
- Remove redundant brew function in zshrc
- Add new plugins and configurations for Neovim
- Update lazy-lock.json for Neovim
- Adjust font settings in Wezterm
- Modify tmux configuration for better UI
- Update yabai rules for window management
- Add new file for tmux-nerd-font-window-name configuration
- Add new plugins for Wakatime and CopilotChat in Neovim
- Remove certain providers in Neovim options
- Add new gitignore file for stow
- Update install.sh script with new tools and path changes
- Modify hammerspoon configurations
- Update tmux.conf with new settings and plugins
- Add new configurations for yabairc
- Adjust PATH in zshrc
- Rename and modify certain git configuration files
- Update bin scripts for better functionality and UI
- Modify Neovim and Wezterm configurations for better font rendering and UI
- Add new plugin configuration file for CopilotChat in Neovim
- Modify Neotree plugin configuration in Neovim for better UI
- Add new plugin configuration file for Wakatime in Neovim
- Add new tmux-nerd-font-window-name configuration file in tmux
- Modify yabairc for better window management rules
- Update PATH in zshrc for icu4c
- Remove certain providers in Neovim options
- Add new gitignore file for stow
- Update install.sh script with new tools and path changes
- Modify hammerspoon configurations
- Update tmux.conf with new settings and plugins
- Add new configurations for yabairc
- Adjust PATH in zshrc
- Rename and modify certain git configuration files
- Update bin scripts for better functionality and UI
- Modify Neovim and Wezterm configurations for better font rendering and UI
- Add new plugin configuration file for CopilotChat in Neovim
- Modify Neotree plugin configuration in Neovim for better UI
- Add new plugin configuration file for Wakatime in Neovim
- Add new tmux-nerd-font-window-name configuration file in tmux
- Modify yabairc for better window management rules
- Update PATH in zshrc for icu4c

diff --git a/bin/bin/update-yabai b/bin/bin/update-yabai
--- a/bin/bin/update-yabai
+++ b/bin/bin/update-yabai
@@ -1,18 +1,52 @@
-#!/bin/bash
+#!/bin/sh
 
-echo "yabai updating..."
+gum style \
+    --foreground 12 --border-foreground 12 --border double \
+    --align center --width 60 --margin "1 0" --padding "1 0" \
+    ' ██╗   ██╗██████╗ ██████╗  █████╗ ████████╗███████╗
+ ██║   ██║██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝
+██║   ██║██████╔╝██║  ██║███████║   ██║   █████╗
+██║   ██║██╔═══╝ ██║  ██║██╔══██║   ██║   ██╔══╝
+╚██████╔╝██║     ██████╔╝██║  ██║   ██║   ███████╗
+ ╚═════╝ ╚═╝     ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝'
 
-# set codesigning certificate name here (default: yabai-cert)
-export YABAI_CERT=
+NOW=$(date +"%Y-%m-%d-%H-%M-%S")
+echo -e "$NOW\n" >>/tmp/u-$NOW.txt
 
 # stop yabai
 yabai --stop-service
 
 # reinstall yabai
-brew reinstall koekeishiya/formulae/yabai
-codesign -fs "${YABAI_CERT:-yabai-cert}" "$(brew --prefix yabai)/bin/yabai"
+gum spin --spinner globe --title "🍻 brew updating yabai" --show-output -- brew reinstall koekeishiya/formulae/yabai >>/tmp/u-$NOW.txt
 
-sudo bash -c 'echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" > /private/etc/sudoers.d/yabai'
+WHOAMI=$(whoami)
+# Get the SHA-256 hash of the yabai program
+YABAI_PATH=$(which yabai)
+if [ -z "$YABAI_PATH" ]; then
+    echo " yabai not found!"
+    exit 1
+fi
+HASH=$(shasum -a 256 "$YABAI_PATH" | awk '{print $1}') >>/tmp/u-$NOW.txt
+
+# Check if HASH is non-empty
+if [ -z "$HASH" ]; then
+    echo " Failed to get hash for yabai!"
+    exit 1
+fi
+
+# Construct the new sudoers entry
+SUDOERS_ENTRY="$WHOAMI ALL=(root) NOPASSWD: sha256:$HASH $YABAI_PATH --load-sa"
+
+# Write the entry to /private/etc/sudoers.d/yabai
+echo "$SUDOERS_ENTRY" | sudo tee /private/etc/sudoers.d/yabai >>/tmp/u-$NOW.txt
+
+# Set the appropriate permissions for the sudoers file
+sudo chmod 0440 /private/etc/sudoers.d/yabai >>/tmp/u-$NOW.txt
+
+echo "Updated /private/etc/sudoers.d/yabai successfully!"
 
 # finally, start yabai
 yabai --start-service
+
+echo "✅ 🧾 logged to /tmp/u-$NOW.txt"
+
